/**
 * Hebrew rows of the bundled lexicon, ascending by Mispar Hechrachi value.
 *
 * Rows sourced `'sepher-sephiroth'` are transcribed from Crowley's ASCII
 * transliteration of *Sepher Sephiroth* (Equinox I(8), 1912) with the key
 * A א, B ב, G ג, D ד, H ה, V ו, Z ז, Ch ח, T ט, Y י, K כ, L ל, M מ, N נ, S ס,
 * a'a ע, P פ, Tz צ, Q ק, R ר, Sh ש, Th ת (finals written where Hebrew
 * orthography requires them; the transliteration does not mark them). Every row's
 * letters were checked against that transliteration and its value is recomputed
 * with `he-hechrachi` in the test suite. Glosses are short identifications, not
 * Crowley's commentary; the modern editorial notes interleaved in the e-text are
 * excluded.
 */

import type { LexiconRow } from './rows.js'

export const HEBREW_ROWS: readonly LexiconRow[] = [
  ['אב', 3, 'father', 'sepher-sephiroth'],
  ['אבא', 4, 'father (Aramaic)', 'sepher-sephiroth'],
  ['גד', 7, 'Gad; good fortune', 'sepher-sephiroth'],
  ['אח', 9, 'brother', 'sepher-sephiroth'],
  ['הה', 10, 'window; the letter He spelled', 'sepher-sephiroth'],
  ['וו', 12, 'Vau; hook, nail', 'sepher-sephiroth'],
  ['אחד', 13, 'echad — One / Unity', 'sepher-sephiroth'],
  ['אהבה', 13, 'ahavah — love', 'sepher-sephiroth', 'echad = ahavah = 13'],
  ['יד', 14, 'hand', 'sepher-sephiroth'],
  ['דוד', 14, 'David; beloved', 'sepher-sephiroth'],
  ['זהב', 14, 'gold', 'sepher-sephiroth'],
  ['הוד', 15, 'Hod; splendour (8th Sephirah)', 'sepher-sephiroth'],
  ['יה', 15, 'Yah', 'sepher-sephiroth'],
  ['טוב', 17, 'good', 'sepher-sephiroth'],
  ['חי', 18, 'chai — life', 'sepher-sephiroth'],
  ['אהיה', 21, 'Eheieh, I am (Kether name)', 'sepher-sephiroth'],
  ['חיה', 23, 'life', 'sepher-sephiroth'],
  ['יהוה', 26, 'YHVH — the Tetragrammaton', 'sepher-sephiroth'],
  ['כח', 28, 'power', 'sepher-sephiroth'],
  ['יהודה', 30, 'Judah', 'sepher-sephiroth'],
  ['אל', 31, 'El — God', 'sepher-sephiroth', 'the Key of 31 (with לא/AL)'],
  ['לא', 31, 'lo — not', 'sepher-sephiroth', 'the Key of 31 (LA/AL)'],
  ['לב', 32, 'lev — heart', 'sepher-sephiroth', '32 paths of wisdom'],
  ['כבוד', 32, 'glory', 'sepher-sephiroth'],
  ['אגלא', 35, 'AGLA', 'sepher-sephiroth'],
  ['הבל', 37, 'Abel; breath, vanity', 'sepher-sephiroth'],
  ['יחידה', 37, 'Yechidah', 'sepher-sephiroth'],
  ['טל', 39, 'dew', 'sepher-sephiroth'],
  ['כוזו', 39, 'Avgad of YHVH', 'sepher-sephiroth', 'Avgad (metathesis) of יהוה'],
  ['אם', 41, 'mother', 'sepher-sephiroth'],
  ['אלוה', 42, 'Eloah', 'sepher-sephiroth'],
  ['אמא', 42, 'Ama, the Supernal Mother', 'sepher-sephiroth'],
  ['גדול', 43, 'great', 'sepher-sephiroth'],
  ['דם', 44, 'blood', 'sepher-sephiroth'],
  ['אדם', 45, 'Adam; man', 'sepher-sephiroth', 'Aiq Beker exchange of אמת (441)'],
  ['מה', 45, 'Mah', 'sepher-sephiroth', 'the MAH Milui of YHVH = 45'],
  ['אגיאל', 45, 'Agiel, intelligence of Saturn', 'agrippa', '= זזאל Zazel = 45'],
  ['גדולה', 48, 'Gedulah; greatness', 'sepher-sephiroth'],
  ['כוכב', 48, 'Kokab; star, sphere of Mercury', 'sepher-sephiroth'],
  ['ים', 50, 'sea', 'sepher-sephiroth'],
  ['כל', 50, 'all', 'sepher-sephiroth'],
  ['בן', 52, 'Ben; son', 'sepher-sephiroth', 'the BAN Milui of YHVH = 52'],
  ['אימא', 52, 'Aima, the Supernal Mother', 'sepher-sephiroth'],
  ['אבן', 53, 'stone', 'sepher-sephiroth'],
  ['גן', 53, 'garden', 'sepher-sephiroth'],
  ['יום', 56, 'day', 'sepher-sephiroth'],
  ['מזבח', 57, 'altar', 'sepher-sephiroth'],
  ['חן', 58, 'grace', 'sepher-sephiroth'],
  ['אין', 61, 'Ain — Nothing / the Negative', 'sepher-sephiroth'],
  ['אדון', 61, 'Adon, lord', 'sepher-sephiroth'],
  ['אני', 61, 'I', 'sepher-sephiroth'],
  ['אבדון', 63, 'Abaddon', 'sepher-sephiroth'],
  ['דין', 64, 'Din; justice', 'sepher-sephiroth'],
  ['נוגה', 64, 'Nogah; sphere of Venus', 'sepher-sephiroth'],
  ['נבואה', 64, 'prophecy', 'sepher-sephiroth'],
  ['אדני', 65, 'Adonai — Lord', 'sepher-sephiroth'],
  ['היכל', 65, 'palace', 'sepher-sephiroth'],
  ['בינה', 67, 'Binah; understanding (3rd Sephirah)', 'sepher-sephiroth'],
  ['סוד', 70, 'secret', 'sepher-sephiroth'],
  ['יין', 70, 'wine', 'sepher-sephiroth'],
  ['יונה', 71, 'dove; Jonah', 'sepher-sephiroth'],
  ['חסד', 72, 'Chesed; mercy (4th Sephirah)', 'sepher-sephiroth'],
  ['עב', 72, 'Ab (AB milui)', 'sepher-sephiroth', 'the AB Milui of YHVH = 72'],
  ['חכמה', 73, 'Chokmah — Wisdom (2nd Sephirah)', 'sepher-sephiroth'],
  ['למד', 74, 'Lamed; ox-goad', 'sepher-sephiroth'],
  ['נויט', 75, 'Nuit', 'sepher-sephiroth'],
  ['לילה', 75, 'night', 'sepher-sephiroth'],
  ['הילל', 75, 'Lucifer, the herald star', 'sepher-sephiroth'],
  ['מזל', 77, 'mazal; influence', 'sepher-sephiroth'],
  ['לחם', 78, 'bread', 'sepher-sephiroth'],
  ['בעז', 79, 'Boaz', 'sepher-sephiroth'],
  ['יאחין', 79, 'Jachin', 'sepher-sephiroth'],
  ['יסוד', 80, 'Yesod; foundation (9th Sephirah)', 'sepher-sephiroth'],
  ['אנכי', 81, 'I (Anokhi)', 'sepher-sephiroth'],
  ['לבן', 82, 'Laban; white', 'sepher-sephiroth'],
  ['חנוך', 84, 'Enoch', 'sepher-sephiroth'],
  ['פה', 85, 'Pe; mouth', 'sepher-sephiroth', 'the letter Pe, spelled PH'],
  ['אלהים', 86, 'Elohim — God (plural)', 'sepher-sephiroth'],
  ['הללויה', 86, 'Hallelujah', 'sepher-sephiroth'],
  ['לבנה', 87, 'Levanah; the moon, sphere of the Moon', 'sepher-sephiroth'],
  ['מים', 90, 'water', 'sepher-sephiroth'],
  ['מלך', 90, 'king', 'sepher-sephiroth'],
  ['אמן', 91, 'Amen', 'sepher-sephiroth'],
  ['מלאך', 91, 'angel', 'sepher-sephiroth'],
  ['צבא', 93, 'host, army', 'sepher-sephiroth'],
  ['מלכה', 95, 'queen', 'sepher-sephiroth'],
  ['מאדים', 95, 'Madim; Mars', 'sepher-sephiroth'],
  ['בן אדם', 97, 'son of man', 'sepher-sephiroth'],
  ['כף', 100, 'Kaph; palm', 'sepher-sephiroth'],
  ['מיכאל', 101, 'Michael', 'sepher-sephiroth'],
  ['אמונה', 102, 'faith', 'sepher-sephiroth'],
  ['נון', 106, 'Nun; fish', 'sepher-sephiroth'],
  ['גיהנם', 108, 'Gehinnom', 'sepher-sephiroth'],
  ['אלף', 111, 'aleph spelled in full — ox / thousand', 'sepher-sephiroth', '111'],
  ['פלא', 111, 'wonder (title of Kether)', 'sepher-sephiroth'],
  ['נכיאל', 111, 'Nakhiel, intelligence of the Sun', 'agrippa'],
  ['יהוה אלהים', 112, 'YHVH Elohim', 'sepher-sephiroth'],
  ['סמך', 120, 'Samekh; prop', 'sepher-sephiroth'],
  ['עין', 130, 'Ayin; eye', 'sepher-sephiroth'],
  ['סמאל', 131, 'Samael', 'sepher-sephiroth'],
  ['הסמאל', 136, 'Hismael, spirit of Jupiter', 'agrippa', '= יהפיאל Yophiel = 136'],
  ['קבלה', 137, 'Qabalah', 'sepher-sephiroth'],
  ['בן אלהים', 138, 'son of God', 'sepher-sephiroth'],
  ['בליעל', 142, 'Belial', 'sepher-sephiroth'],
  ['עולם', 146, 'olam; world, eternity', 'sepher-sephiroth'],
  ['נצח', 148, 'Netzach; victory (7th Sephirah)', 'sepher-sephiroth'],
  ['אלף הה יוד הה', 151, 'AHYH spelled in full', 'sepher-sephiroth'],
  [
    'באבאלען',
    156,
    "Babalon (Crowley's Hebrew, BABALa'aN)",
    'sepher-sephiroth',
    '= Greek Βαβαλον = 156',
  ],
  ['ציון', 156, 'Zion', 'sepher-sephiroth'],
  ['יוסף', 156, 'Joseph', 'sepher-sephiroth'],
  ['כסף', 160, 'silver', 'sepher-sephiroth'],
  ['עץ', 160, 'tree', 'sepher-sephiroth'],
  ['קין', 160, 'Cain', 'sepher-sephiroth'],
  ['עליון', 166, 'Elyon; the Most High', 'sepher-sephiroth'],
  [
    'קדמאל',
    175,
    'Kedemel, spirit of Venus',
    'sepher-sephiroth',
    'Agrippa prints 157; 175 is the Venus square line sum',
  ],
  ['גן עדן', 177, 'Garden of Eden', 'sepher-sephiroth'],
  ['אור', 207, 'or — light', 'curated'],
  ['רוח', 214, 'ruach — spirit / breath', 'curated'],
  ['שדי', 314, 'Shaddai — the Almighty', 'mathers', '= מטטרון Metatron = 314'],
  ['מטטרון', 314, 'Metatron (= שדי Shaddai 314)', 'mathers', '= שדי Shaddai = 314'],
  ['משיח', 358, 'Mashiach — Messiah', 'mathers', 'MShICh = 358 (Mathers)'],
  ['נחש', 358, 'nachash — serpent', 'curated', 'nachash = Mashiach = 358'],
  ['יבא שילה', 358, "'Shiloh shall come' (= משיח 358)", 'mathers', '= משיח = 358'],
  ['שלמה', 375, 'Solomon', 'sepher-sephiroth'],
  ['שלום', 376, 'shalom — peace', 'sepher-sephiroth'],
  ['ישוע', 386, 'Yeshua; Jesus', 'sepher-sephiroth'],
  ['צירוף', 386, 'Tziruph (temurah table)', 'sepher-sephiroth'],
  ['שמים', 390, 'heaven', 'sepher-sephiroth'],
  ['את', 401, "Ath; essence, 'the'", 'sepher-sephiroth'],
  ['אתה', 406, 'Atah; Thou', 'sepher-sephiroth'],
  ['קדוש', 410, 'holy', 'sepher-sephiroth'],
  ['בית', 412, 'Beth; house', 'sepher-sephiroth'],
  ['אין סוף אור', 414, 'Ain Soph Aur, the Limitless Light', 'sepher-sephiroth'],
  ['אבראהאדאברא', 418, 'ABRAHADABRA', 'sepher-sephiroth', 'the Word of the Aeon; 418'],
  ['חית', 418, 'Cheth; fence', 'sepher-sephiroth'],
  ['בולשכין', 418, 'Boleskine', 'sepher-sephiroth'],
  ['אריך אנפין', 422, 'Arikh Anpin, the Vast Countenance', 'sepher-sephiroth'],
  ['נפש', 430, 'Nephesh', 'sepher-sephiroth'],
  ['תהו ובהו', 430, 'Tohu va-Bohu', 'sepher-sephiroth'],
  ['נוטריקון', 431, 'Notariqon', 'sepher-sephiroth'],
  ['דלת', 434, 'Daleth; door', 'sepher-sephiroth'],
  ['אמת', 441, 'emeth — truth', 'sepher-sephiroth', 'Aiq Beker exchange of אדם (45)'],
  ['אילת', 441, 'hind (cerva)', 'sepher-sephiroth'],
  ['מקדש', 444, 'sanctuary', 'sepher-sephiroth'],
  ['מות', 446, 'death', 'sepher-sephiroth'],
  ['תהום', 451, 'the Abyss', 'sepher-sephiroth'],
  ['בהמות', 453, 'Behemoth', 'sepher-sephiroth'],
  ['דעת', 474, 'Daath; knowledge', 'sepher-sephiroth'],
  ['זעיר אנפין', 478, 'Zeir Anpin, the Lesser Countenance', 'sepher-sephiroth'],
  ['לילית', 480, 'Lilith', 'sepher-sephiroth'],
  ['מלכות', 496, 'Malkuth; kingdom (10th Sephirah)', 'sepher-sephiroth'],
  ['לויתן', 496, 'Leviathan', 'sepher-sephiroth'],
  ['צבאות', 499, 'Tzabaoth; hosts', 'sepher-sephiroth'],
  ['ראש', 501, 'head', 'sepher-sephiroth'],
  ['ריש', 510, 'Resh; head', 'sepher-sephiroth'],
  ['שיר', 510, 'song', 'sepher-sephiroth'],
  ['יהוה צבאות', 525, 'YHVH Tzabaoth', 'sepher-sephiroth'],
  ['תורה', 611, 'Torah — the Law', 'curated'],
  ['כתר', 620, 'Kether — Crown (1st Sephirah)', 'curated'],
  ['סורת', 666, 'Sorath, spirit of the Sun', 'agrippa'],
]
